name: reuse-test

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          file: graph_ql_example/Dockerfile
          context: graph_ql_example/
          tags: hoge
          load: true
          target: development
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: pytest
        run: cd graph_ql_example && docker run -v $(pwd)/:/app/ hoge pytest

  pytest:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: ls
        run: ls
      - name: docker build
        run: cd graph_ql_example && docker build . -t hoge
      - name: pytest
        run: docker run -v $(pwd)/:/app/ hoge pytest
